### ISSUE TITLE
Make it possible to train without needing an adjustment defined in the experiment

### ISSUE THREAD

**Issue by some-rando-rl** [AechPro/distrib-rl#9]
RIght now to run training we need to have some adjustment in the experiment in order to train, even if we want to keep our hyperparameters fixed.

We can work around this easily enough, but experiment files for training will be more readable w/o that.

**Comment by some-rando-rl** [comment]
I think this is likely just a matter of making it so that `RunServer` can accept a path to a config file instead of an experiment file, and then train ad infinitum from there.

**Comment by nevercast** [comment]
Could the experiment just have no adjustments defined? I like the decoupled experiments / environments.

**Comment by some-rando-rl** [comment]
I spoke with @AechPro today about a plan of attack for handling resuming training with and without hyperparam modifications, and I think this issue is likely no longer relevant. I'm going to close this and open one that's a bit more reflective of what we discussed.
